# Generated by Django 4.1.2 on 2022-10-29 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_remove_country_states_remove_state_cities_city_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='state_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='geo.country'),
        ),
    ]
