# Generated by Django 4.1.2 on 2022-10-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_alter_country_country_id_alter_state_state_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
